### ISSUE TITLE
Single Settings Orchestration File

### ISSUE THREAD

**Issue by rmutter** [yeti/yurt#10]
It seems like we could have one orchestration `settings.yml` env_vars file that gets copied to `development.yml`, `vagrant.yml`, `production.yml` etc with the proper variables replaced. Right now since we have one settings file for each, if we want to edit those we'd have to edit each of them.

**Comment by paolopaolopaolo** [comment]
Using the `yurt remote_server` flow fixes this. We now add server targets ad-hoc rather than set them all up at the beginning.
