### ISSUE TITLE
Make Yurt Python 3 Compatible

### ISSUE THREAD

**Issue by rmutter** [yeti/yurt#13]

**Comment by paolopaolopaolo** [comment]
@baylee This might be referring to Yurt being run on Python 3, not just creating Python 3 projects. Is this right @rmutter, or can we close this?

**Comment by rmutter** [comment]
Let's close it, there's issues with Yurt being python 3 right?

**Comment by paolopaolopaolo** [comment]
@rmutter, yup. Fabric doesn't work all the time with Python 3 (or rather, it is "untested")!
