### ISSUE TITLE
Latest Release Version is Broken

### ISSUE THREAD

**Issue by rmutter** [yeti/yurt#96]
Looks like more updates have been made since the last version of Yurt was released, which fixed some bugs. Specifically here `orchestration/roles/db/tasks/main.yml`, `with_items: "{{ private_application_hosts|default([]) }}"` needed to have the `default([])`.

I think this'll be fixed if you just cut a new release.

**Comment by paolopaolopaolo** [comment]
New Release cut! Maybe it's not broken anymore.
